#################################
# Version & seed settings
#################################

version: "default"    # is used for log-folder name
seed: 1               # data sampling and weights initialization

#################################
# System settings
#################################

# equation coefficients
alpha: -1.0
beta: 1.0
delta: 1.0

# Initial Angle (in degrees)
x0: 0.2
# Initial Velocity
x_t0: 0.2

# Simulation Length
T: 10

#################################
# Data settings (sampled anewly at each epoch)
#################################

N_col: 1024

#################################
# PhysicsInformedNN settings
#################################

N_hidden: 4
N_neurons: 50
activation: 'swish'

N_epochs: 25000
learning_rate: 0.001
decay_rate: 1.0

#################################
# Callback and Log settings
#################################

freq_log: 100
freq_print: 1000
keys_print: ['loss_P', 'loss_IC']
freq_save: 1000

#################################
# Regularization settings
#################################
regularizer: "no_reg"
reg_coeff: 0.0
reg_decay: "linear"
reg_epochs: 0.5