#################################
# Version & seed settings
#################################

version: "default"    # is used for log-folder name
seed: 1               # data sampling and weights initialization

#################################
# System settings
#################################

# Initial Condition
y0: 0.1
# Simulation Length
T: 10

#################################
# Data settings (sampled anewly at each epoch)
#################################

N_col: 1024

#################################
# PhysicsInformedNN settings
#################################

N_hidden: 4
N_neurons: 50
activation: 'swish'

#################################
# Training settings
#################################

N_epochs: 50000
learning_rate: 0.001
decay_rate: 1.0

#################################
# Callback and Log settings
#################################

freq_log: 100
freq_print: 1000
keys_print: ['loss']
freq_save: 100

#################################
# Regularization settings
#################################

regularization: "reg_derivative"
reg_coeff: 1
reg_decay: 1
reg_epochs: 1