#################################
# Version & seed settings
#################################

version: "default"    # is used for log-folder name
seed: 1               # data sampling and weights initialization

#################################
# System settings
#################################

# Initial Condition
y0: 0.2
# Simulation Length
T: 20

#################################
# Data settings (sampled anewly at each epoch)
#################################

N_col: 4096

#################################
# PhysicsInformedNN settings
#################################

N_hidden: 6
N_neurons: 100
activation: 'swish'

#################################
# Training settings
#################################

N_epochs: 20000
learning_rate: 0.001
decay_rate: 1.0

#################################
# Callback and Log settings
#################################

freq_log: 10
freq_print: 100
keys_print: ['loss']